### ISSUE TITLE
Make the bootstrap noop when merge detected

### ISSUE THREAD

**Issue by iandunn** [coreymckrill/nearby-wordpress-events#31]
The bootstrapper should check if the WP instance that the plugin is running inside has merged the feature proposal, and then quit early, to avoid trying to redefine functions, etc.

**Comment by iandunn** [comment]
91f03ec adds the early return, with my best-guess at to what we can use to detect if it's been merged. We should revisit this once we start building the merge patch, though, to make sure it will detect it. 

Worst case, we can always add a `wp_fetch_nearby_events()` to `deprecated.php` in order to make sure it works. I'll need to make another commit to `require` that file, though.

**Comment by iandunn** [comment]
@dd32, do 91f03ec and 5f0367d seem like a good noop solution for the merge?

**Comment by dd32** [comment]
Seems fine to me, although the detection method feels a little hacky.. but this was always going to be a hacky thing to detect, and isn't something we've sorted out how to deal with yet.

I should say that I don't think either of the function names being tested feels right for core, `fetch` is an odd term to be using in a core function I feel, `wp_get_nearby_events()` might be more wp-like.

**Comment by iandunn** [comment]
Ah, ok, thanks! I went with `fetch` because it seemed to imply that the source of the data was remote rather than local, but I'll change it to `get` so that it's consistent with Core's convention.

**Comment by iandunn** [comment]
This is causing fatals during async uploads:

`PHP Fatal error:  Cannot redeclare wp_ajax_search_install_plugins() (previously declared in wp-admin/includes/ajax-actions.php:3870) in wp-admin/includes/ajax-actions.php on line 3870`

`async-uploads.php` calls `include( ABSPATH . 'wp-admin/includes/ajax-actions.php' )` instead of using `include_once()` 😞 

We'll probably need to add an extra condition to the early return at the start of the file, to include a check for `SCRIPT_FILENAME` being `index.php`.

**Comment by iandunn** [comment]
Fixed in 76013991b73d388fc1f733fb20a82bbe05fe656a
