### ISSUE TITLE
a11y: don't use placeholders as replacement for labels

### ISSUE THREAD

**Issue by afercia** [coreymckrill/nearby-wordpress-events#33]
See also https://core.trac.wordpress.org/ticket/40331

For accessibility, placeholder attributes should not be used as replacements for labels. It's far better to display a visible label and remove the placeholder:

<img width="657" alt="screen shot 2017-04-17 at 17 16 12" src="https://cloud.githubusercontent.com/assets/1682452/25093330/1ec168b4-2392-11e7-9911-440aa10b4d27.png">

**Comment by iandunn** [comment]
Great point.

@mapk, how do you feel about us adding a `City: ` label to the left of the input field, and then changing the placeholder to something like `Vancouver, Toronto, Quebec`? (The specific cities would be set by translators, and we would ask them to pick cities in their locale and write them in that locale's language).

**Comment by mapk** [comment]
Good idea. Let's do it.
