### ISSUE TITLE
Let local teams link to their own meetup organizer page

### ISSUE THREAD

**Issue by naokomc** [coreymckrill/nearby-wordpress-events#38]
There is a hard-coded link to make./community: https://make.wordpress.org/community/handbook/meetup-organizer/welcome/

Source: https://github.com/coreymckrill/nearby-wordpress-events/blob/f3f566af9a45a07351693ca29d638b573a1e33d5/includes/dashboard-widget.php#L157

I think it's better if this link is translatable to a local resource page.
There is much better chance that non-English users (especially those who may not be super technical or polyglots) decide to get involved with event organization if they are sent to a doc written in their language.

Alternatively, the handbook page itself can have links to available translated pages.

**Comment by iandunn** [comment]
That's a good point, thanks!
