### ISSUE TITLE
Don't load plugin on non-Dashboard screens

### ISSUE THREAD

**Issue by iandunn** [coreymckrill/nearby-wordpress-events#39]
We return early on the front-end instead of unnecessarily loading the plugin, but we should also return early on non-Dashboard screens, for the same reasons.

**Comment by coreymckrill** [comment]
Doesn't [this](https://github.com/coreymckrill/nearby-wordpress-events/blob/master/nearby-wordpress-events.php#L35) take care of unnecessary loading in wp-admin? Perhaps we just need to move the file includes inside of that hooked function?

**Comment by iandunn** [comment]
Doh, you're right. Good catch :)
