### ISSUE TITLE
Improve the spinner position

### ISSUE THREAD

**Issue by afercia** [coreymckrill/nearby-wordpress-events#40]
When the spinner appears, it's a bit far from the Submit button:

<img width="654" alt="screen shot 2017-04-22 at 12 35 40" src="https://cloud.githubusercontent.com/assets/1682452/25304819/5175fb7c-276f-11e7-916a-8a0bedbe2d63.png">

Spinners are floated right by default, I think a few properties would be enough to have this spinner close to the right of the button:
```
float: none;
vertical-align: top;
margin-left: 0;
```

**Comment by iandunn** [comment]
I can't see anything left to do here after 7350e6e, so I'm going to close it. Feel free to re-open if anyone spots anything that's still needed.
