### ISSUE TITLE
Error messages audible feedback and styling

### ISSUE THREAD

**Issue by afercia** [coreymckrill/nearby-wordpress-events#41]
When errors occur, there's no audible feedback for screen reader users. After they submit, and some error happens, they won't have a clue what just happened. It would be great to consider to use `wp.a11y.speak()` to make the error messages available to assistive technologies.

About styling, maybe the errors could use some `notice` styling?

<img width="654" alt="screen shot 2017-04-22 at 12 38 51" src="https://cloud.githubusercontent.com/assets/1682452/25304857/35f1d67c-2770-11e7-924f-22ed6647d144.png">

<img width="656" alt="screen shot 2017-04-22 at 12 42 07" src="https://cloud.githubusercontent.com/assets/1682452/25304858/35f4aa28-2770-11e7-8662-2ffb025003bd.png">

**Comment by afercia** [comment]
Ideally, also when the response returns results successfully, there should be an audible feedback to inform users the list of event has been updated.

**Comment by iandunn** [comment]
@afercia I started down this road in the `41-speak` branch, with a9add33, but now I'm wondering if I'm doing it right.

Even if we add `speak()` calls for the error messages, there's still a lot of other content which isn't being announced, like the event names, times, etc after a successful AJAX request.

Would it be better to add `aria-live` regions directly to the templates themselves, so that the screen reader automatically announces the changes? I would imagine that would be more useful, since all of the changes would be announces.

**Comment by afercia** [comment]
@iandunn hi, when experimenting with the first implementations of aria-live in core, we've initially tried to add `aria-live` directly to a UI section that got updated. That resulted in a ton of content that got announced, basically "bombarding" users with huge, overwhelming, messages. I think the ticket was https://core.trac.wordpress.org/ticket/27555 were `aria-live` was set on the list of tags in the tags meta box. We then realized that wasn't a good approach 🙂 

> Even if we add speak() calls for the error messages, there's still a lot of other content which isn't being announced, like the event names, times, etc after a successful AJAX request.

I think in these cases, all users need is to be informed the list of events has been updated. Then, they can easily find the list below the form. A bit of content exploration is definitely acceptable when the updated content can be easily found in a place that makes sense!

**Comment by iandunn** [comment]
Ah, ok, that makes sense. Thanks!

I'll add more `speak()` calls to cover the other cases where the content changes.

**Comment by iandunn** [comment]
Note to self: still need to add more `speak()`s, add styling, and make sure that there isn't a `speak()` when the page first loads with an error state.

Related #46

**Comment by iandunn** [comment]
7e23f69 looks good, especially the parts about moving the `speak()` calls into the render function.

The only thing I'm wondering is if maybe we should have a separate message for when the location is found, but there aren't any upcoming events?

`The city was updated. Now listing upcoming events near %s` implies that events were found, so it might be a bit awkward if the user then listened to the `nearbywp-results` section and it said there weren't any events.

What do you all think?

**Comment by coreymckrill** [comment]
First I tried having two separate `wp.speak` calls, one for the changed location and one for the events. But VoiceOver kept skipping the first one and only reading the second one.

I tried combining them into one call, but then it just seemed really verbose. @afercia said this:

> A bit of content exploration is definitely acceptable when the updated content can be easily found in a place that makes sense!

...so I figured it might be better to just leave it simple and let the screen reader read the "There are no events at this location" message when they navigate down to it.

That said, I'm certainly open to adding info about the events back in.

**Comment by iandunn** [comment]
> First I tried having two separate wp.speak calls

Do you mean something like this?

```js
wp.a11y.speak( nearbyWPData.i18n.cityUpdated ) );
if ( templateParams.events.length ) {
	template = wp.template( 'nearbywp-event-list' );
	$results.html( template( templateParams ) );
	wp.a11y.speak( nearbyWPData.i18n.listingEventsNear.replace( /%s/g, templateParams.location.description ) );
} else {
	template = wp.template( 'nearbywp-no-upcoming-events' );
	$results.html( template( templateParams ) );
}
```

I was picturing something more like this:

```js
if ( templateParams.events.length ) {
	template = wp.template( 'nearbywp-event-list' );
	$results.html( template( templateParams ) );
	wp.a11y.speak( nearbyWPData.i18n.cityUpdated.replace( /%s/g, templateParams.location.description ) );
} else {
	template = wp.template( 'nearbywp-no-upcoming-events' );
	$results.html( template( templateParams ) );
	wp.a11y.speak( nearbyWPData.i18n.noUpcomingEvents );
}
```

I'm not sure if that'd be good or not, though.

**Comment by coreymckrill** [comment]
I meant the first one. It seems like a good idea to notify that the location has changed regardless of whether there are any events associated with the new city.

The second example could still do that. We could have two separate message strings that look something like this:

```php
'cityUpdatedEvents' => __( 'The city was updated. Now listing upcoming events near %s.', 'nearby-wp-events' ),
'cityUpdatedNoEvents' => __( 'The city was updated. Currently there are no upcoming events near %s.', 'nearby-wp-events' ),
```

**Comment by iandunn** [comment]
Yeah, that sounds good to me if it sounds good to you.

**Comment by afercia** [comment]
The shorter the better :)

**Comment by iandunn** [comment]
Would it be better to just say `The city was updated.` and let them explore to find the rest of the info?

**Comment by afercia** [comment]
Typically, screen readers announce changes of states, elements, etc. with very short messages. FOr instance: `button expanded` and not `The button was expanded` :) Doesn't need to be proper, formal English. Trying a good balance between short an informative:
`'cityUpdatedEvents' => __( 'City updated. Listing upcoming events near %s.', 'nearby-wp-events' ),` or something similar.

Also, I've noticed the aria-label says `Edit location` while both the visible label and the messages use `City`. I'd consider to use always the same term, location or city.

**Comment by iandunn** [comment]
Thanks! I fixed the label in e8df5e4. I'll work on making the spoken messages more brief.

**Comment by iandunn** [comment]
> Note to self: still need to add more speak()s, add styling, and make sure that there isn't a speak() when the page first loads with an error state.

Those are all done now, and I shortened the messages in 6967367, so I think this issue is all sorted, unless you notice any other problems @afercia

**Comment by afercia** [comment]
@iandunn messages look good to me, thanks!

- unrelated 1: it is possible to submit the form leaving the input field empty, I guess this is not the desired behavior
- unrelated2: probably others will have thoughts about the strong and italic used for one translatable string and for the related visible notice, but thats out of the scope of this issue

**Comment by iandunn** [comment]
> messages look good to me,

Thanks! I'll close this issue.

> probably others will have thoughts about the strong and italic used for one translatable string and for the related visible notice, but thats out of the scope of this issue

Oh, I didn't even think of potential issues there. The uses weren't very intentional, they just seemed helpful at the time, but I'm definitely open to changing them. What in particular do you think could be problems with those?

**Comment by afercia** [comment]
For translators, preferably strings should not contain HTML. I've seen lots of tickets stripping out HTML to be replaced with placeholders recently.
Also visually, bold+italic and generally italic are maybe a bit too much but I'm not a designer so I'd leave that to the design folks :)

**Comment by iandunn** [comment]
Ah, I see. I've always kept the surrounding HTML out of the string, but didn't realize that Core was using placeholders for inline tags now. I removed all but one of the `<em>`s in [the merge patch](https://gist.github.com/iandunn/d2569bdfc70f671062db83548d2f4168), but haven't backported it here yet.
