### ISSUE TITLE
Improve the no-js notice

### ISSUE THREAD

**Issue by afercia** [coreymckrill/nearby-wordpress-events#42]
When JS is off, the widget displays a notice message `This widget requires JavaScript.`

<img width="654" alt="screen shot 2017-04-22 at 13 04 31" src="https://cloud.githubusercontent.com/assets/1682452/25305362/3ebf0568-277a-11e7-956b-65fd48075aa9.png">

In a few other places in the admin, this kind of "no-js" notices use the CSS notice classes, it would be nice for consistency if also the Events and News widget would use them:

<img width="513" alt="screen shot 2017-04-22 at 13 06 16" src="https://cloud.githubusercontent.com/assets/1682452/25305366/4c8066d8-277a-11e7-8c7e-5c38ca3976d1.png">

<img width="629" alt="screen shot 2017-04-22 at 13 07 54" src="https://cloud.githubusercontent.com/assets/1682452/25305367/4c8207c2-277a-11e7-8cf3-daf5ff9608b5.png">

Ouch, the current News widget notice 🙂 

<img width="654" alt="screen shot 2017-04-22 at 13 13 14" src="https://cloud.githubusercontent.com/assets/1682452/25305368/4c84ac16-277a-11e7-82d4-670b3016b98f.png">

I'm going to open a Trac ticket for the current News widget, this issue is just to keep track of the changes that will probably need to ported here too.

**Comment by afercia** [comment]
See https://core.trac.wordpress.org/ticket/40529

**Comment by coreymckrill** [comment]
We could just add the `error` class to that notice:

<img width="495" alt="js-required" src="https://cloud.githubusercontent.com/assets/916023/25352851/424a908a-28e2-11e7-94cc-1e33d23d488e.png">

It doesn't have the padding that the admin notice errors have, but it's also inside a widget. I think it looks better without the padding.

**Comment by afercia** [comment]
Actually, when JS is off nothing  will be displayed under the notice, so it would look a bit differently. See the patch on the WP Trac ticket.

<img width="652" alt="ouw_1p4zbd" src="https://cloud.githubusercontent.com/assets/1682452/25356120/6d1693c0-2939-11e7-8476-adf0ec0ea73f.png">
