### ISSUE TITLE
Error displayed when page first loads and no location available

### ISSUE THREAD

**Issue by iandunn** [coreymckrill/nearby-wordpress-events#46]
If no events/location are cached, the `error occurred...` error is displayed to users. It'd be better UX to just display the `Enter your closest city name...` message.

**Comment by coreymckrill** [comment]
> If no events/location are cached, the error occurred... error is displayed to users.

I think there is an additional condition for the error message to appear, that there isn't a valid IP address available, which happens for example when you're running the widget on a Vagrant box. If I hard-code my actual public IP address from my ISP, and clear out all the cached data, I don't get the error message, but rather it guesses a location near my ISP.

**Comment by iandunn** [comment]
I think there other situations where the geolocation fails, though, like with IPv6 addresses.
